import { Inter } from 'next/font/google';
import SessionProvider from './pages/api/auth/SessionProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-900">
      <body className="h-full">
        <SessionProvider>
          <div className={inter.className}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
